### PR TITLE
Change Directory to call default search

### PR DESCRIPTION
**Pull request by gilbertocampos**
This PR 
- adds a new GET endpoint to SearchController that returns the “default” view (pagination / sort only)
- updates the Directory page to GET the new  Search URL instead of Profile
- updates the `vw_StaffSearch.sql` to add additional columns in result

**Note: Currently `vw_StaffSearch` is returning no results even without filtering so Directory will be displaying no results**

### CODE REVIEW

**Comment by pmcvtm** [comment]
MUST: It looks like the query is executing correctly up-front, but when I sort by `school` `position` `highestDegree` or `major` the API is returning an error. Looks like a `KeyNotFound` under the hood, probably we need to change the column names on one side or the other?

Here's an example stack trace:
```
2021-08-04 10:35:16.724 -05:00 [ERR] The given key 'position' was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key 'position' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LeadershipProfileAPI.Data.EdFiDbQueryData.GetSearchResultsAsync(ProfileSearchRequestBody body, String sortBy, String sortField, Int32 currentPage, Int32 pageSize) in C:\dev\msdf\Leadership-Profile\src\API\LeadershipProfileAPI\Data\EdFiDbQueryData.cs:line 98
   at LeadershipProfileAPI.Features.Search.List.QueryHandler.Handle(Query request, CancellationToken cancellationToken) in C:\dev\msdf\Leadership-Profile\src\API\LeadershipProfileAPI\Features\Search\List.cs:line 71
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at LeadershipProfileAPI.Features.Search.SearchController.GetProfile(ProfileSearchRequestQuery query, CancellationToken cancellationToken) in C:\dev\msdf\Leadership-Profile\src\API\LeadershipProfileAPI\Features\Search\SearchController.cs:line 51
   at lambda_method298(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by gilbertocampos** [comment]
@pmcvtm  sort by `school ` `position` `highestDegree` and `major ` fixed, added/updated the column-field mapping

**Review by pmcvtm — APPROVED** [review]
Looks great, thank you!

**Comment by pmcvtm** [comment]
A note for future readers: We're digging into the data mapping and a new sample data set so these query changes might not be _quite_ right, but this change unblocks us for using the sample data as configured in the repo currently.

**Pull request merged**
