### PR TITLE
LPV-45 Sorting feature was removed

### PR DESCRIPTION
**Pull request by josemtzb**
The sorting feature was removed from the Directory page.
It was removed from all the columns except the "Name Column"

### CODE REVIEW

**Review by gilbertocampos — COMMENTED** [review]
SHOULD:
I think if we're no longer going to filter in the UI we might as well remove the sortings in the backend and just leave id (current default) and name (the only one with a UI control). That can be found in `EdFiDbQueryData` the `fieldMapping `dictionary in `GetSearchResultsAsync` method.

**Comment by pmcvtm** [comment]
> SHOULD:
> I think if we're no longer going to filter in the UI we might as well remove the sortings in the backend and just leave id (current default) and name (the only one with a UI control). That can be found in `EdFiDbQueryData` the `fieldMapping `dictionary in `GetSearchResultsAsync` method.

While generally I agree with this (removing API options to match front-end) I am thinking we may want to leave it in in case an org that forks this repo wants to sort by other columns (to keep the option open). If we don't think that's likely, we might want to go a step further and change the request to remove the `SortField` entirely, and just keep asc / desc (maybe renamed `SortOrder`, and either change the default to be by name, or include `null` to keep `id`. Let's check in on the context for the request to remove this about what makes sense.

**Review by pmcvtm — APPROVED** [review]
Confirmed we are OK to leave the different sort options in the API to keep the app extensible in the event it gets forked.

**Comment by pmcvtm** [comment]
COULD: Add `SortField` option values as constants in front-end.

Especially since we're removing the other options, it would be helpful to make it obvious what those values are. They probably ought to be an enum on the back-end as well, to add some baseline validation for it. We can follow up to changes these.

**Pull request merged**
