### PR TITLE
Build Script

### PR DESCRIPTION
**Pull request by javierg85**
* Adds a psake script to build, test the project and run the database migrations using RoundHouse.
* Adds a database backup on the testdata folder to make the project easier to develop and test.
* When the tests are invoked, a docker container with a test database is run. It can be used for integration tests.
* When building the project, it creates a zip file for the API and another one for the frontend in the artifacts folder.
* The app version is calculated using the MinVer CLI

### CODE REVIEW

**Comment by stephenfuqua** [comment]
@javierg85 @YogirajA as discussed at project inception, I would like to get more information / input from others about psake. I have only ever seen it in very old projects, and have never heard anyone actually talk about it. That leaves me with a negative, though perhaps unwarranted, impression. I will try to take a look at it tomorrow and will query some folks on the Ed-Fi development teams to get their impressions, if any.

Can we also move the test data out to another platform and rewrite that commit, so that we're not uploading a large binary file into the repository? I can help with that by hosting the zip file on the Ed-Fi Azure account, for example. If we can agree to this, then the commit needs to be rewritten, rather than just delete the file, so that the file doesn't remain in git history.

**Review by stephenfuqua — CHANGES_REQUESTED** [review]
At minimum, requesting removal of the zip file. This file already exists in the Ed-Fi azure account, at https://odsassets.blob.core.windows.net/public/TPDM/EdFi_TPDM_v08_20201109.zip

**Comment by javierg85** [comment]
> At minimum, requesting removal of the zip file. This file already exists in the Ed-Fi azure account, at https://odsassets.blob.core.windows.net/public/TPDM/EdFi_TPDM_v08_20201109.zip

Removed the zip file and updated the build script to download it from the URL.

**Review by stephenfuqua — APPROVED** [review]
Thank you for addressing the zip file. 

I looked at psake last night and at first glance I can see the appeal. I've been able to get input on it from several other senior devs working Ed-Fi projects. What I heard from them is that it can be easy to overuse psake dependencies, thus making it difficult to reason about what is going on. They also pointed me to other newer/cross platform build tools, such as cake and nuke.build. 

It is clear that there is little appetite for using psake in Ed-Fi's core projects. However, I did not hear enough concern that I'm going to push back any further on this leadership profile application.

**Comment by YogirajA** [comment]
@stephenfuqua Thanks for your feedback. I apologize for the delayed response. We looked into other tools and discussed them during our status meetings with Itzel. We didn't see a huge gain in switching to other tools. If anything changes there and the time permits, we will make the necessary changes.

**Review by YogirajA — APPROVED** [review]

**Pull request merged**
