### PR TITLE
Remove Location column from Directory

### PR DESCRIPTION
**Pull request by gilbertocampos**
This Pull Request removes the "Location" column from the Directory table grid

### CODE REVIEW

**Comment by pmcvtm** [comment]
SHOULD: Remove other uses of Location

Updating the UI gets the job done, but we've want to go 'deep' on removing fields, so we're not left with unused code elsewhere in the app.

- [ ] in the card view change `location` to `institution`
- [ ] in the API remove the `Location` property on `ProfileList` and in `GetProfileList`

A note: Looks like if someone wants to know `Location`, it's still on the main profile page so we should be good to remove it from the above.

**Comment by gilbertocampos** [comment]
SHOULD We also update the icon from the card view from the GeoIcon to EducationIcon to reflect what the new location is?
image
image

@pmcvtm

**Comment by pmcvtm** [comment]
> SHOULD We also update the icon from the card view from the GeoIcon to EducationIcon to reflect what the new location is?

Yeah, let's go ahead and change that to match. Good catch!

**Comment by gilbertocampos** [comment]
Updated:
- Removed Location from Profile in API and related tests
- Switched location to institution in profile card, updated icon as well

**Review by pmcvtm — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
